# Generated by Django 3.0.6 on 2020-06-14 22:24

import central.formatChecker
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('subject', models.CharField(max_length=120)),
                ('comment', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TagChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('------', '------'), ('ui_tag', 'UI tag'), ('bke_tag', 'Backend Tag'), ('algo_tag', 'Algorithm Tag'), ('frb_tag', 'FreeProject Tag'), ('prm_tag', 'Premium Tag'), ('tips_tag', 'Tips Tag')], default='------', max_length=100)),
            ],
            options={
                'verbose_name': 'Tag Choices',
                'verbose_name_plural': 'Tag Choices',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('------', '------'), ('ui', 'UI/UX'), ('backend', 'Backend'), ('algorithm', 'Algorithm'), ('freebies', 'Free Projects'), ('premium', 'Premium'), ('video', 'Video'), ('tips_n_tricks', 'Tips & Tricks')], default='------', max_length=100)),
                ('badges', models.CharField(choices=[('------', '------'), ('python', 'Python'), ('javascript', 'Javascript'), ('all', 'All')], default='------', max_length=100)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text=' \n\t\t  When django prepopulate slugs, it normally omits prepositions, do not forget\n\t\t  to add it manually\n\t\t', null=True, unique=True)),
                ('image', central.formatChecker.ContentTypeRestrictedFileField(help_text=' @Upload image(png, webp, jpeg and svg) with 1200 x 600 (dm) & size 100kb or less', upload_to='post_images/%Y/%m/%d/')),
                ('content', froala_editor.fields.FroalaField(help_text='\n\t\t\t\t\t\t\t\t1. Change mode to Code View and add class="prettyprint beautify" \n\t\t\t\t\t\t\t\tto pre tag for elegant code highlighting.\n\t\t\t\t\t\t\t\t')),
                ('draft', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url_tracking', models.TextField(blank=True, max_length=2000, null=True, verbose_name='URL')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Hits')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='Read Time')),
                ('meta_description', models.TextField(max_length=10000)),
                ('tags', models.ManyToManyField(to='central.TagChoices')),
            ],
            options={
                'ordering': ['-timestamp', '-last_updated'],
            },
        ),
    ]
